displayName=NoWieldNoWearInBank
author=Welkon
description=Removes the wield and wear options from items whilst in your bank
tags=bank,wield,wear,equip,armor,menu,qol
version=1.0.0
plugins=com.example.NoWieldInBankPlugin
build=standard