displayName=NoMisclicksInBank
author=Welkon
description=Removes the wield, wear, drink, and eat options from items whilst in your bank
tags=bank,misclick,wield,wear,drink,eat,food,equip,menu,qol
version=1.0.1
plugins=com.example.NoWieldInBankPlugin
build=standard